version: '3'
services:

  mongo:
    container_name: mongo
    image: "mongo"
    restart: always 
    volumes:
      - "databases:/data/db"
      - "backup:/backup"
      - "backup:/mongorestore"
    ports:
      - "27017:27017"

  adminmongo:
    image: "webts/adminmongo"
    restart: always
    environment:
      - CONN_NAME=mongo
      - DB_HOST=mongo
      - PORT=8082
    ports:
      - "8082:8082"
    links:
      - mongo